[licenses]
unlicensed = "deny"
copyleft = "deny"
allow-osi-fsf-free = "either"
confidence-threshold = 0.8
allow = [
    "Apache-2.0",
    "MIT",
    "CC0-1.0",
    "ISC",
    "0BSD",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "Unlicense",
    "Unicode-DFS-2016",
    "Unicode-3.0",
]

[bans]
multiple-versions = "deny"
highlight = "all"
allow = []
deny = []
skip = []
skip-tree = []

[advisories]
notice = "deny"
unmaintained = "deny"
unsound = "deny"
vulnerability = "deny"
